site_name: reqtrace
site_description: A GitOps-friendly requirements tracing tool.
site_url: https://philipmiesbauer.github.io/reqtrace/
repo_url: https://github.com/philipmiesbauer/reqtrace

theme:
  name: lux
  features:
    - navigation.tabs
    - navigation.indexes
    - search.suggest
    - search.highlight

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - API Reference:
    - CLI: api/cli.md
    - Coverage: api/coverage.md
    - Models: api/models.md
    - Parser: api/parser.md
    - Scanner: api/scanner.md
